### PR TITLE
Fix extracted directory

### PR DESCRIPTION
**Pull request by ivankravets**

### CODE REVIEW

**Comment by ilg-ul** [comment]
thank you!

**Comment by ivankravets** [comment]
Thank you too for all your scripts!

**Comment by ilg-ul** [comment]
You are welcome. Did you see the [gnuarmeclipse/build-scripts ](https://github.com/gnuarmeclipse/build-scripts)?

**Comment by ivankravets** [comment]
That has been a place from the which I came here 😊 

Do you have already pre-compiled openOCD 0.10 somewhere?

**Comment by ilg-ul** [comment]
http://gnuarmeclipse.github.io/openocd/

**Comment by ivankravets** [comment]
Wow! I've just done for macOS. Thanks a lot from @PlatformIO Community!

**Comment by ivankravets** [comment]
@ilg-ul How is difficult to add support for OpenOCD ARM? Currently, I use Vagrant+Arch and native chroot-ing. I see that your prefer Docker. My configuration looks something like,
```
      # .....

      # Process ARCH RPi image
      if [ ! -d "archlinux-rpi" ]
      then
        wget http://archlinuxarm.org/os/ArchLinuxARM-rpi-latest.tar.gz -O ArchLinuxARM-rpi-latest.tar.gz
        rm -rf archlinux-rpi
        mkdir archlinux-rpi
        bsdtar -xpf ArchLinuxARM-rpi-latest.tar.gz -C archlinux-rpi
      fi

      sudo update-binfmts --enable qemu-arm
      cp /usr/bin/qemu-arm-static archlinux-rpi/usr/bin
      sudo arch-chroot archlinux-rpi uname -m
      # upgrade system
      sudo arch-chroot archlinux-rpi pacman -Syu --noconfirm

      # .....
      sudo arch-chroot archlinux-rpi CMD ARGS
```

**Comment by ilg-ul** [comment]
I doubt that it is that simple, and for the very limited audience I'm not sure it is worth the effort.

but, if you like to adapt the script to suit your needs, feel free to do it.

**Pull request merged**
